# GAITREC Dataset | Data Import Notebook

In [ ]:
# Copyright (C)  2019  Djordje Slijepcevic
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

In [1]:
import pandas as pd

In [2]:
# Left lower extremity
GRF_F_V_PRO_left = pd.read_csv(r'GRF_F_V_PRO_left.csv')
#GRF_F_V_RAW_left = pd.read_csv(r'GRF_F_V_RAW_left.csv')

GRF_F_AP_PRO_left = pd.read_csv(r'GRF_F_AP_PRO_left.csv')
#GRF_F_AP_RAW_left = pd.read_csv(r'GRF_F_AP_RAW_left.csv')

GRF_F_ML_PRO_left = pd.read_csv(r'GRF_F_ML_PRO_left.csv')
#GRF_F_ML_RAW_left = pd.read_csv(r'GRF_F_ML_RAW_left.csv')

GRF_COP_AP_PRO_left = pd.read_csv(r'GRF_COP_AP_PRO_left.csv')
#GRF_COP_AP_RAW_left = pd.read_csv(r'GRF_COP_AP_RAW_left.csv')

GRF_COP_ML_PRO_left = pd.read_csv(r'GRF_COP_ML_PRO_left.csv')
#GRF_COP_ML_RAW_left = pd.read_csv(r'GRF_COP_ML_RAW_left.csv')

# Right lower extremity
GRF_F_V_PRO_right = pd.read_csv(r'GRF_F_V_PRO_right.csv')
#GRF_F_V_RAW_right = pd.read_csv(r'GRF_F_V_RAW_right.csv')

GRF_F_AP_PRO_right = pd.read_csv(r'GRF_F_AP_PRO_right.csv')
#GRF_F_AP_RAW_right = pd.read_csv(r'GRF_F_AP_RAW_right.csv')

GRF_F_ML_PRO_right = pd.read_csv(r'GRF_F_ML_PRO_right.csv')
#GRF_F_ML_RAW_right = pd.read_csv(r'GRF_F_ML_RAW_right.csv')

GRF_COP_AP_PRO_right = pd.read_csv(r'GRF_COP_AP_PRO_right.csv')
#GRF_COP_AP_RAW_right = pd.read_csv(r'GRF_COP_AP_RAW_right.csv')

GRF_COP_ML_PRO_right = pd.read_csv(r'GRF_COP_ML_PRO_right.csv')
#GRF_COP_ML_RAW_right = pd.read_csv(r'GRF_COP_ML_RAW_right.csv')

# Annotations and Metadata
GRF_Annotation = pd.read_csv(r'GRF_metadata.csv')

In [17]:
GRF_F_V_PRO = pd.concat([GRF_F_V_PRO_left, GRF_F_V_PRO_right], axis = 0)

In [12]:
GRF_F_AP_PRO = pd.concat([GRF_F_AP_PRO_left, GRF_F_AP_PRO_right], axis = 0)

In [13]:
GRF_F_ML_PRO = pd.concat([GRF_F_ML_PRO_left, GRF_F_ML_PRO_right], axis = 0)

In [14]:
GRF_COP_AP_PRO = pd.concat([GRF_COP_AP_PRO_left, GRF_COP_AP_PRO_right], axis = 0)

In [15]:
GRF_COP_ML_PRO = pd.concat([GRF_COP_ML_PRO_left, GRF_COP_ML_PRO_right], axis = 0)

In [22]:
GRF = pd.concat([GRF_F_V_PRO, GRF_F_AP_PRO, GRF_F_ML_PRO, GRF_COP_AP_PRO, GRF_COP_ML_PRO], axis = 0)

In [23]:
GRF

,SUBJECT_ID,SESSION_ID,TRIAL_ID,F_V_PRO_1,F_V_PRO_2,F_V_PRO_3,F_V_PRO_4,F_V_PRO_5,F_V_PRO_6,F_V_PRO_7,...,COP_ML_PRO_92,COP_ML_PRO_93,COP_ML_PRO_94,COP_ML_PRO_95,COP_ML_PRO_96,COP_ML_PRO_97,COP_ML_PRO_98,COP_ML_PRO_99,COP_ML_PRO_100,COP_ML_PRO_101
0,510,413,1,0.022633,0.061113,0.114901,0.176286,0.240173,0.307632,0.381910,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,510,413,2,0.022631,0.064086,0.120122,0.182163,0.247071,0.318845,0.401557,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,510,413,3,0.022629,0.057981,0.105291,0.159700,0.219181,0.285077,0.358567,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,510,413,4,0.022627,0.065699,0.128061,0.203220,0.286525,0.377700,0.476686,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,510,413,6,0.022627,0.065287,0.124876,0.192132,0.262683,0.339977,0.428425,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75727,93,999910375,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.003047,-0.003313,-0.003743,-0.004275,-0.004800,-0.005188,-0.005299,-0.005299,-0.005299,-0.005299
75728,93,999910375,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.004003,-0.004232,-0.004604,-0.005023,-0.005402,-0.005747,-0.005848,-0.005848,-0.005848,-0.005848
75729,93,999910375,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.001912,-0.001252,-0.000770,-0.000542,-0.000526,-0.000625,-0.000744,-0.000795,-0.000796,-0.000796
75730,93,999910375,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.001577,-0.001426,-0.001594,-0.002089,-0.002765,-0.003435,-0.003886,-0.003912,-0.003912,-0.003912
75731,93,999910375,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.007129,-0.005977,-0.004770,-0.003618,-0.002610,-0.001820,-0.001331,-0.001103,-0.001056,-0.001056

In [24]:
merged = pd.merge(GRF, GRF_Annotation, on="SESSION_ID")

In [25]:
merged.to_csv("merged.csv", mode = 'w', index=False)

In [26]:
merged

,SUBJECT_ID_x,SESSION_ID,TRIAL_ID,F_V_PRO_1,F_V_PRO_2,F_V_PRO_3,F_V_PRO_4,F_V_PRO_5,F_V_PRO_6,F_V_PRO_7,...,AFFECTED_SIDE,SHOD_CONDITION,ORTHOPEDIC_INSOLE,SPEED,READMISSION,SESSION_TYPE,SESSION_DATE,TRAIN,TRAIN_BALANCED,TEST
0,510,413,1,0.022633,0.061113,0.114901,0.176286,0.240173,0.307632,0.381910,...,2.0,1,NaN,2,0,1,26.01.2007,1,0,0
1,510,413,2,0.022631,0.064086,0.120122,0.182163,0.247071,0.318845,0.401557,...,2.0,1,NaN,2,0,1,26.01.2007,1,0,0
2,510,413,3,0.022629,0.057981,0.105291,0.159700,0.219181,0.285077,0.358567,...,2.0,1,NaN,2,0,1,26.01.2007,1,0,0
3,510,413,4,0.022627,0.065699,0.128061,0.203220,0.286525,0.377700,0.476686,...,2.0,1,NaN,2,0,1,26.01.2007,1,0,0
4,510,413,6,0.022627,0.065287,0.124876,0.192132,0.262683,0.339977,0.428425,...,2.0,1,NaN,2,0,1,26.01.2007,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
757315,93,999910375,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0.0,3,0,1,28.08.2017,1,0,0
757316,93,999910375,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0.0,3,0,1,28.08.2017,1,0,0
757317,93,999910375,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0.0,3,0,1,28.08.2017,1,0,0
757318,93,999910375,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0.0,3,0,1,28.08.2017,1,0,0
757319,93,999910375,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0.0,3,0,1,28.08.2017,1,0,0

In [13]:
combined_data = pd.concat([GRF_F_V_PRO_right, GRF_F_AP_PRO_right, GRF_F_ML_PRO_right, GRF_COP_AP_PRO_right, GRF_COP_ML_PRO_right, GRF_F_V_PRO_left, GRF_F_AP_PRO_left, GRF_F_ML_PRO_left, GRF_COP_AP_PRO_left, GRF_COP_ML_PRO_left], axis = 0)

In [15]:
combined_data

,SUBJECT_ID,SESSION_ID,TRIAL_ID,F_V_PRO_1,F_V_PRO_2,F_V_PRO_3,F_V_PRO_4,F_V_PRO_5,F_V_PRO_6,F_V_PRO_7,...,COP_ML_PRO_92,COP_ML_PRO_93,COP_ML_PRO_94,COP_ML_PRO_95,COP_ML_PRO_96,COP_ML_PRO_97,COP_ML_PRO_98,COP_ML_PRO_99,COP_ML_PRO_100,COP_ML_PRO_101
0,510,413,1,0.022642,0.066304,0.123147,0.178585,0.229816,0.286079,0.353620,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,510,413,2,0.022637,0.063175,0.114420,0.163122,0.207777,0.257460,0.317920,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,510,413,3,0.022628,0.066277,0.123461,0.178248,0.225705,0.274257,0.330758,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,510,413,4,0.022641,0.067567,0.130535,0.199452,0.267539,0.337289,0.411577,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,510,413,6,0.022629,0.065415,0.122248,0.179967,0.232711,0.285586,0.346265,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75727,93,999910375,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.005587,-0.005406,-0.005352,-0.005382,-0.005468,-0.005573,-0.005645,-0.005670,-0.005671,-0.005671
75728,93,999910375,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.000539,-0.000541,-0.000629,-0.000774,-0.000985,-0.001311,-0.001804,-0.002097,-0.002097,-0.002097
75729,93,999910375,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.003953,-0.004198,-0.004754,-0.005638,-0.006878,-0.008332,-0.009778,-0.010676,-0.010676,-0.010676
75730,93,999910375,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.000650,-0.000408,-0.000381,-0.000569,-0.000939,-0.001446,-0.001952,-0.002108,-0.002108,-0.002108
75731,93,999910375,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.003923,0.004419,0.004891,0.005313,0.005666,0.005943,0.006146,0.006276,0.006315,0.006315

In [16]:
clean_data_all = pd.merge(combined_data, GRF_Annotation, on="SESSION_ID")

In [17]:
clean_data_all

,SUBJECT_ID_x,SESSION_ID,TRIAL_ID,F_V_PRO_1,F_V_PRO_2,F_V_PRO_3,F_V_PRO_4,F_V_PRO_5,F_V_PRO_6,F_V_PRO_7,...,AFFECTED_SIDE,SHOD_CONDITION,ORTHOPEDIC_INSOLE,SPEED,READMISSION,SESSION_TYPE,SESSION_DATE,TRAIN,TRAIN_BALANCED,TEST
0,510,413,1,0.022642,0.066304,0.123147,0.178585,0.229816,0.286079,0.353620,...,2.0,1,NaN,2,0,1,26.01.2007,1,0,0
1,510,413,2,0.022637,0.063175,0.114420,0.163122,0.207777,0.257460,0.317920,...,2.0,1,NaN,2,0,1,26.01.2007,1,0,0
2,510,413,3,0.022628,0.066277,0.123461,0.178248,0.225705,0.274257,0.330758,...,2.0,1,NaN,2,0,1,26.01.2007,1,0,0
3,510,413,4,0.022641,0.067567,0.130535,0.199452,0.267539,0.337289,0.411577,...,2.0,1,NaN,2,0,1,26.01.2007,1,0,0
4,510,413,6,0.022629,0.065415,0.122248,0.179967,0.232711,0.285586,0.346265,...,2.0,1,NaN,2,0,1,26.01.2007,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
757315,93,999910375,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0.0,3,0,1,28.08.2017,1,0,0
757316,93,999910375,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0.0,3,0,1,28.08.2017,1,0,0
757317,93,999910375,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0.0,3,0,1,28.08.2017,1,0,0
757318,93,999910375,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0.0,3,0,1,28.08.2017,1,0,0
757319,93,999910375,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0.0,3,0,1,28.08.2017,1,0,0

In [18]:
clean_data_all.to_csv("clean_data_all.csv", mode = 'w', index=False)

In [2]:
df = pd.read_csv("clean_data_all.csv")

In [5]:
# reduce the size of dataframe
df = pd.reduce(df)

AttributeError: module 'pandas' has no attribute 'reduce'

In [3]:
df

,SUBJECT_ID_x,SESSION_ID,TRIAL_ID,F_V_PRO_1,F_V_PRO_2,F_V_PRO_3,F_V_PRO_4,F_V_PRO_5,F_V_PRO_6,F_V_PRO_7,...,AFFECTED_SIDE,SHOD_CONDITION,ORTHOPEDIC_INSOLE,SPEED,READMISSION,SESSION_TYPE,SESSION_DATE,TRAIN,TRAIN_BALANCED,TEST
0,510,413,1,0.022642,0.066304,0.123147,0.178585,0.229816,0.286079,0.353620,...,2.0,1,NaN,2,0,1,26.01.2007,1,0,0
1,510,413,2,0.022637,0.063175,0.114420,0.163122,0.207777,0.257460,0.317920,...,2.0,1,NaN,2,0,1,26.01.2007,1,0,0
2,510,413,3,0.022628,0.066277,0.123461,0.178248,0.225705,0.274257,0.330758,...,2.0,1,NaN,2,0,1,26.01.2007,1,0,0
3,510,413,4,0.022641,0.067567,0.130535,0.199452,0.267539,0.337289,0.411577,...,2.0,1,NaN,2,0,1,26.01.2007,1,0,0
4,510,413,6,0.022629,0.065415,0.122248,0.179967,0.232711,0.285586,0.346265,...,2.0,1,NaN,2,0,1,26.01.2007,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
757315,93,999910375,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0.0,3,0,1,28.08.2017,1,0,0
757316,93,999910375,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0.0,3,0,1,28.08.2017,1,0,0
757317,93,999910375,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0.0,3,0,1,28.08.2017,1,0,0
757318,93,999910375,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0.0,3,0,1,28.08.2017,1,0,0
757319,93,999910375,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0.0,3,0,1,28.08.2017,1,0,0

## Processed Data

In [22]:
#new = pd.merge(df1, df2, on="SESSION_ID")

In [19]:
combined_left = pd.concat([GRF_F_V_PRO_left, GRF_F_AP_PRO_left, GRF_F_ML_PRO_left, GRF_COP_AP_PRO_left, GRF_COP_ML_PRO_left], axis = 0)

In [20]:
left_clean_data_all = pd.merge(combined_left, GRF_Annotation, on="SESSION_ID")

In [21]:
left_clean_data_all.to_csv("left_clean_data_all.csv", mode = 'w', index=False)

In [24]:
combined_right = pd.concat([GRF_F_V_PRO_right, GRF_F_AP_PRO_right, GRF_F_ML_PRO_right, GRF_COP_AP_PRO_right, GRF_COP_ML_PRO_right], axis = 0)

In [25]:
right_clean_data_all = pd.merge(combined_right, GRF_Annotation, on="SESSION_ID")

In [26]:
right_clean_data_all.to_csv("right_clean_data_all.csv", mode = 'w', index=False)

In [54]:
combined_left.to_csv("combined_left.csv")

In [52]:
combined_right = pd.concat([GRF_F_V_PRO_right, GRF_F_AP_PRO_right, GRF_F_ML_PRO_right, GRF_COP_AP_PRO_right, GRF_COP_ML_PRO_right, GRF_F_V_PRO_left, GRF_F_AP_PRO_left, GRF_F_ML_PRO_left, GRF_COP_AP_PRO_left, GRF_COP_ML_PRO_left], axis = 0)

In [53]:
combined_right

,SUBJECT_ID,SESSION_ID,TRIAL_ID,F_V_PRO_1,F_V_PRO_2,F_V_PRO_3,F_V_PRO_4,F_V_PRO_5,F_V_PRO_6,F_V_PRO_7,...,COP_ML_PRO_92,COP_ML_PRO_93,COP_ML_PRO_94,COP_ML_PRO_95,COP_ML_PRO_96,COP_ML_PRO_97,COP_ML_PRO_98,COP_ML_PRO_99,COP_ML_PRO_100,COP_ML_PRO_101
0,510,413,1,0.022642,0.066304,0.123147,0.178585,0.229816,0.286079,0.353620,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,510,413,2,0.022637,0.063175,0.114420,0.163122,0.207777,0.257460,0.317920,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,510,413,3,0.022628,0.066277,0.123461,0.178248,0.225705,0.274257,0.330758,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,510,413,4,0.022641,0.067567,0.130535,0.199452,0.267539,0.337289,0.411577,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,510,413,6,0.022629,0.065415,0.122248,0.179967,0.232711,0.285586,0.346265,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75727,93,999910375,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.003047,-0.003313,-0.003743,-0.004275,-0.004800,-0.005188,-0.005299,-0.005299,-0.005299,-0.005299
75728,93,999910375,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.004003,-0.004232,-0.004604,-0.005023,-0.005402,-0.005747,-0.005848,-0.005848,-0.005848,-0.005848
75729,93,999910375,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.001912,-0.001252,-0.000770,-0.000542,-0.000526,-0.000625,-0.000744,-0.000795,-0.000796,-0.000796
75730,93,999910375,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.001577,-0.001426,-0.001594,-0.002089,-0.002765,-0.003435,-0.003886,-0.003912,-0.003912,-0.003912
75731,93,999910375,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.007129,-0.005977,-0.004770,-0.003618,-0.002610,-0.001820,-0.001331,-0.001103,-0.001056,-0.001056

In [55]:
combined_right.to_csv("combined_right.csv")

In [56]:
combined_left_right = pd.concat([combined_left, combined_right], axis = 0)

In [2]:
combined_left_right.to_csv("combined_left_right.csv")

NameError: name 'combined_left_right' is not defined

In [3]:
combined_left_right = pd.read_csv("combined_left_right.csv")

In [4]:
GRF_metadata = pd.read_csv("GRF_metadata.csv")

In [6]:
clean_data_all = pd.merge(combined_left_right, GRF_metadata, on="SESSION_ID")

In [9]:
clean_data_all.describe()

,Unnamed: 0,SUBJECT_ID_x,SESSION_ID,TRIAL_ID,F_V_PRO_1,F_V_PRO_2,F_V_PRO_3,F_V_PRO_4,F_V_PRO_5,F_V_PRO_6,...,SHOE_SIZE,AFFECTED_SIDE,SHOD_CONDITION,ORTHOPEDIC_INSOLE,SPEED,READMISSION,SESSION_TYPE,TRAIN,TRAIN_BALANCED,TEST
count,757320.000000,757320.000000,7.573200e+05,757320.000000,151464.000000,151464.000000,151464.000000,151464.000000,151464.000000,151464.000000,...,483790.000000,679770.000000,757320.000000,703580.000000,757320.000000,757320.000000,757320.000000,757320.000000,757320.000000,757320.000000
mean,37865.500000,1183.208327,3.167849e+06,5.733864,0.032047,0.080415,0.147111,0.221506,0.293979,0.363432,...,42.177649,0.568280,0.981052,0.114017,2.004648,0.075952,1.715404,0.696469,0.083294,0.303531
std,21861.959725,715.032160,5.376973e+07,2.988728,0.006702,0.019430,0.043596,0.071959,0.098738,0.121692,...,2.486288,0.591103,0.326997,0.317832,0.259870,0.290820,0.488081,0.459783,0.276326,0.459783
min,0.000000,1.000000,4.130000e+02,1.000000,0.014992,0.025481,0.028835,0.031838,0.036330,0.043242,...,35.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000
25%,18932.750000,533.000000,1.604200e+04,3.000000,0.027131,0.066509,0.116730,0.171049,0.223536,0.276097,...,41.000000,0.000000,1.000000,0.000000,2.000000,0.000000,1.000000,0.000000,0.000000,0.000000
50%,37865.500000,1189.000000,2.305200e+04,6.000000,0.031276,0.077592,0.139449,0.208704,0.277783,0.346457,...,43.000000,1.000000,1.000000,0.000000,2.000000,0.000000,2.000000,1.000000,0.000000,0.000000
75%,56798.250000,1817.000000,2.994800e+04,8.000000,0.036084,0.091381,0.169554,0.259507,0.348980,0.433193,...,44.000000,1.000000,1.000000,0.000000,2.000000,0.000000,2.000000,1.000000,0.000000,1.000000
max,75731.000000,2392.000000,9.999104e+08,18.000000,0.066162,0.240709,0.464667,0.719171,0.938989,1.135012,...,50.000000,2.000000,2.000000,1.000000,3.000000,3.000000,3.000000,1.000000,1.000000,1.000000

In [ ]:
clean_data_all.to_csv("clean_data_all.csv")